// <auto-generated />
namespace ConsoleApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RecreatedatabaseinAzureSQLServer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecreatedatabaseinAzureSQLServer));
        
        string IMigrationMetadata.Id
        {
            get { return "201602090452134_Recreate database in Azure SQL Server."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
